### ISSUE TITLE
Font won't install on Windows 10

### ISSUE THREAD

**Issue by chris-velox** [jonathonf/solbera-dnd-fonts#4] opened 2019-03-20 01:00 UTC
Windows 10 claims this file isn't a valid font file. I tried running it through a converter to .ttf, but that doesn't work. Typing letters yields small boxes in MS Word.

**Comment by jonathonf** [comment] 2019-03-29 01:04
This sounds like a duplicate of the other issue: https://github.com/jonathonf/solbera-dnd-fonts/issues/1

Can you confirm whether it's the same thing? If it's not, can you detail why?

**Comment by chris-velox** [comment] 2019-03-29 15:40
This does sound like a duplicate. My apologies.

**Closed** 2019-04-27 14:06 UTC
